# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ecommerce
  labels:
    app: flask-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ecommerce
  template:
    metadata:
      labels:
        app: flask-ecommerce
    spec:
      containers:
      - name: flask-ecommerce
        image: <your-dockerhub-username>/flask-ecommerce:latest
        ports:
        - containerPort: 5000
