# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-ecommerce-service
spec:
  selector:
    app: flask-ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
